# Docker Compose File for Docker Setup
# Author: Garrett Haldrup
# Description: Set up all containers with all required build configuration

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./website:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    restart: unless-stopped

  php:
    build:
      context: .
      dockerfile: DockerFile.php 
    container_name: php
    volumes:
      - ./website:/var/www/html
    restart: unless-stopped

  db:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: weatherdb
      MYSQL_USER: weatheruser
      MYSQL_PASSWORD: "1234"
      TZ: America/New_York
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    ports:
      - "3306:3306"

  collector:
    build: ./collector
    privileged: true
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ./scripts:/app/scripts
      - /sys/class/gpio:/sys/class/gpio
      - /dev:/dev
    devices:
      - /dev/gpiochip0
      - /dev/gpiochip4
      - /dev/gpiochip10
      - /dev/gpiochip11
      - /dev/gpiochip12
      - /dev/gpiochip13

volumes:
  db_data: